spring:
  application:
    name: 20_SpringData_StoredProcedure_MySQL_App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Kansas*123
    url: jdbc:mysql://localhost:3306/47_springbootms_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
