spring:
  application:
    name: SpringBoot_Excel_Export
  datasource:
    username: root
    password: Kansas*123
    url: jdbc:mysql://localhost:3306/47_springbootms_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
      
